// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.foodzoneclient.protocols;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodzone_protocols.ClientMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 opcode = 1;</code>
   * @return The opcode.
   */
  int getOpcode();

  /**
   * <pre>
   *Use for login and change password
   * </pre>
   *
   * <code>.foodzone_protocols.LoginInfo account = 2;</code>
   * @return Whether the account field is set.
   */
  boolean hasAccount();
  /**
   * <pre>
   *Use for login and change password
   * </pre>
   *
   * <code>.foodzone_protocols.LoginInfo account = 2;</code>
   * @return The account.
   */
  com.example.foodzoneclient.protocols.LoginInfo getAccount();

  /**
   * <code>.foodzone_protocols.RegisterInfo regAcc = 3;</code>
   * @return Whether the regAcc field is set.
   */
  boolean hasRegAcc();
  /**
   * <code>.foodzone_protocols.RegisterInfo regAcc = 3;</code>
   * @return The regAcc.
   */
  com.example.foodzoneclient.protocols.RegisterInfo getRegAcc();

  /**
   * <code>.foodzone_protocols.Order order = 4;</code>
   * @return Whether the order field is set.
   */
  boolean hasOrder();
  /**
   * <code>.foodzone_protocols.Order order = 4;</code>
   * @return The order.
   */
  com.example.foodzoneclient.protocols.Order getOrder();

  /**
   * <code>.foodzone_protocols.changePassInfo changeRes = 5;</code>
   * @return Whether the changeRes field is set.
   */
  boolean hasChangeRes();
  /**
   * <code>.foodzone_protocols.changePassInfo changeRes = 5;</code>
   * @return The changeRes.
   */
  com.example.foodzoneclient.protocols.changePassInfo getChangeRes();

  public com.example.foodzoneclient.protocols.ClientMessage.ClientRequestsCase getClientRequestsCase();
}
