// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.foodzoneclient.protocols;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodzone_protocols.ClientMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>.foodzone_protocols.LoginRequest loginRequest = 2;</code>
   * @return Whether the loginRequest field is set.
   */
  boolean hasLoginRequest();
  /**
   * <code>.foodzone_protocols.LoginRequest loginRequest = 2;</code>
   * @return The loginRequest.
   */
  com.example.foodzoneclient.protocols.LoginRequest getLoginRequest();

  /**
   * <code>.foodzone_protocols.RegisterRequest registerRequest = 3;</code>
   * @return Whether the registerRequest field is set.
   */
  boolean hasRegisterRequest();
  /**
   * <code>.foodzone_protocols.RegisterRequest registerRequest = 3;</code>
   * @return The registerRequest.
   */
  com.example.foodzoneclient.protocols.RegisterRequest getRegisterRequest();

  /**
   * <code>.foodzone_protocols.UserInfo updateInfoRequest = 4;</code>
   * @return Whether the updateInfoRequest field is set.
   */
  boolean hasUpdateInfoRequest();
  /**
   * <code>.foodzone_protocols.UserInfo updateInfoRequest = 4;</code>
   * @return The updateInfoRequest.
   */
  com.example.foodzoneclient.protocols.UserInfo getUpdateInfoRequest();

  /**
   * <code>.foodzone_protocols.UpdatePasswordRequest updatePasswordRequest = 5;</code>
   * @return Whether the updatePasswordRequest field is set.
   */
  boolean hasUpdatePasswordRequest();
  /**
   * <code>.foodzone_protocols.UpdatePasswordRequest updatePasswordRequest = 5;</code>
   * @return The updatePasswordRequest.
   */
  com.example.foodzoneclient.protocols.UpdatePasswordRequest getUpdatePasswordRequest();

  /**
   * <code>.foodzone_protocols.SubmitOrder submitOrder = 6;</code>
   * @return Whether the submitOrder field is set.
   */
  boolean hasSubmitOrder();
  /**
   * <code>.foodzone_protocols.SubmitOrder submitOrder = 6;</code>
   * @return The submitOrder.
   */
  com.example.foodzoneclient.protocols.SubmitOrder getSubmitOrder();

  /**
   * <code>.foodzone_protocols.RestaurantListRequest restaurantListRequest = 7;</code>
   * @return Whether the restaurantListRequest field is set.
   */
  boolean hasRestaurantListRequest();
  /**
   * <code>.foodzone_protocols.RestaurantListRequest restaurantListRequest = 7;</code>
   * @return The restaurantListRequest.
   */
  com.example.foodzoneclient.protocols.RestaurantListRequest getRestaurantListRequest();

  public com.example.foodzoneclient.protocols.ClientMessage.RequestsCase getRequestsCase();
}
