// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.foodzoneclient.protocols;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodzone_protocols.ClientMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>.foodzone_protocols.LoginRequest loginRequest = 2;</code>
   * @return Whether the loginRequest field is set.
   */
  boolean hasLoginRequest();
  /**
   * <code>.foodzone_protocols.LoginRequest loginRequest = 2;</code>
   * @return The loginRequest.
   */
  com.example.foodzoneclient.protocols.LoginRequest getLoginRequest();

  public com.example.foodzoneclient.protocols.ClientMessage.RequestsCase getRequestsCase();
}
