// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.foodzoneclient.protocols;

/**
 * Protobuf type {@code foodzone_protocols.FoodListResponse}
 */
public  final class FoodListResponse extends
    com.google.protobuf.GeneratedMessageLite<
        FoodListResponse, FoodListResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:foodzone_protocols.FoodListResponse)
    FoodListResponseOrBuilder {
  private FoodListResponse() {
    result_ = "";
    food_ = emptyProtobufList();
  }
  public static final int RESULT_FIELD_NUMBER = 1;
  private java.lang.String result_;
  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  @java.lang.Override
  public java.lang.String getResult() {
    return result_;
  }
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResultBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(result_);
  }
  /**
   * <code>string result = 1;</code>
   * @param value The result to set.
   */
  private void setResult(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    result_ = value;
  }
  /**
   * <code>string result = 1;</code>
   */
  private void clearResult() {
    
    result_ = getDefaultInstance().getResult();
  }
  /**
   * <code>string result = 1;</code>
   * @param value The bytes for result to set.
   */
  private void setResultBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    result_ = value.toStringUtf8();
    
  }

  public static final int FOOD_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.example.foodzoneclient.protocols.FoodInfo> food_;
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.foodzoneclient.protocols.FoodInfo> getFoodList() {
    return food_;
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  public java.util.List<? extends com.example.foodzoneclient.protocols.FoodInfoOrBuilder> 
      getFoodOrBuilderList() {
    return food_;
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  @java.lang.Override
  public int getFoodCount() {
    return food_.size();
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  @java.lang.Override
  public com.example.foodzoneclient.protocols.FoodInfo getFood(int index) {
    return food_.get(index);
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  public com.example.foodzoneclient.protocols.FoodInfoOrBuilder getFoodOrBuilder(
      int index) {
    return food_.get(index);
  }
  private void ensureFoodIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.example.foodzoneclient.protocols.FoodInfo> tmp = food_;
    if (!tmp.isModifiable()) {
      food_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  private void setFood(
      int index, com.example.foodzoneclient.protocols.FoodInfo value) {
    value.getClass();
  ensureFoodIsMutable();
    food_.set(index, value);
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  private void addFood(com.example.foodzoneclient.protocols.FoodInfo value) {
    value.getClass();
  ensureFoodIsMutable();
    food_.add(value);
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  private void addFood(
      int index, com.example.foodzoneclient.protocols.FoodInfo value) {
    value.getClass();
  ensureFoodIsMutable();
    food_.add(index, value);
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  private void addAllFood(
      java.lang.Iterable<? extends com.example.foodzoneclient.protocols.FoodInfo> values) {
    ensureFoodIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, food_);
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  private void clearFood() {
    food_ = emptyProtobufList();
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  private void removeFood(int index) {
    ensureFoodIsMutable();
    food_.remove(index);
  }

  public static com.example.foodzoneclient.protocols.FoodListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.foodzoneclient.protocols.FoodListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.FoodListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.foodzoneclient.protocols.FoodListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.FoodListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.foodzoneclient.protocols.FoodListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.FoodListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.foodzoneclient.protocols.FoodListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.FoodListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.foodzoneclient.protocols.FoodListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.FoodListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.foodzoneclient.protocols.FoodListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.foodzoneclient.protocols.FoodListResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code foodzone_protocols.FoodListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.foodzoneclient.protocols.FoodListResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:foodzone_protocols.FoodListResponse)
      com.example.foodzoneclient.protocols.FoodListResponseOrBuilder {
    // Construct using com.example.foodzoneclient.protocols.FoodListResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public java.lang.String getResult() {
      return instance.getResult();
    }
    /**
     * <code>string result = 1;</code>
     * @return The bytes for result.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultBytes() {
      return instance.getResultBytes();
    }
    /**
     * <code>string result = 1;</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(
        java.lang.String value) {
      copyOnWrite();
      instance.setResult(value);
      return this;
    }
    /**
     * <code>string result = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      copyOnWrite();
      instance.clearResult();
      return this;
    }
    /**
     * <code>string result = 1;</code>
     * @param value The bytes for result to set.
     * @return This builder for chaining.
     */
    public Builder setResultBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setResultBytes(value);
      return this;
    }

    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.foodzoneclient.protocols.FoodInfo> getFoodList() {
      return java.util.Collections.unmodifiableList(
          instance.getFoodList());
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    @java.lang.Override
    public int getFoodCount() {
      return instance.getFoodCount();
    }/**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    @java.lang.Override
    public com.example.foodzoneclient.protocols.FoodInfo getFood(int index) {
      return instance.getFood(index);
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder setFood(
        int index, com.example.foodzoneclient.protocols.FoodInfo value) {
      copyOnWrite();
      instance.setFood(index, value);
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder setFood(
        int index, com.example.foodzoneclient.protocols.FoodInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setFood(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder addFood(com.example.foodzoneclient.protocols.FoodInfo value) {
      copyOnWrite();
      instance.addFood(value);
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder addFood(
        int index, com.example.foodzoneclient.protocols.FoodInfo value) {
      copyOnWrite();
      instance.addFood(index, value);
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder addFood(
        com.example.foodzoneclient.protocols.FoodInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addFood(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder addFood(
        int index, com.example.foodzoneclient.protocols.FoodInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addFood(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder addAllFood(
        java.lang.Iterable<? extends com.example.foodzoneclient.protocols.FoodInfo> values) {
      copyOnWrite();
      instance.addAllFood(values);
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder clearFood() {
      copyOnWrite();
      instance.clearFood();
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder removeFood(int index) {
      copyOnWrite();
      instance.removeFood(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:foodzone_protocols.FoodListResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.foodzoneclient.protocols.FoodListResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "result_",
            "food_",
            com.example.foodzoneclient.protocols.FoodInfo.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0208\u0002\u001b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.foodzoneclient.protocols.FoodListResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.foodzoneclient.protocols.FoodListResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.foodzoneclient.protocols.FoodListResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:foodzone_protocols.FoodListResponse)
  private static final com.example.foodzoneclient.protocols.FoodListResponse DEFAULT_INSTANCE;
  static {
    FoodListResponse defaultInstance = new FoodListResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FoodListResponse.class, defaultInstance);
  }

  public static com.example.foodzoneclient.protocols.FoodListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FoodListResponse> PARSER;

  public static com.google.protobuf.Parser<FoodListResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

