// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.foodzoneclient.protocols;

/**
 * Protobuf type {@code foodzone_protocols.Order}
 */
public  final class Order extends
    com.google.protobuf.GeneratedMessageLite<
        Order, Order.Builder> implements
    // @@protoc_insertion_point(message_implements:foodzone_protocols.Order)
    OrderOrBuilder {
  private Order() {
    username_ = "";
    buyDate_ = "";
    resID_ = "";
    foodList_ = emptyProtobufList();
  }
  public static final int USERNAME_FIELD_NUMBER = 1;
  private java.lang.String username_;
  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>string username = 1;</code>
   * @param value The username to set.
   */
  private void setUsername(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    username_ = value;
  }
  /**
   * <code>string username = 1;</code>
   */
  private void clearUsername() {
    
    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>string username = 1;</code>
   * @param value The bytes for username to set.
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    username_ = value.toStringUtf8();
    
  }

  public static final int BUYDATE_FIELD_NUMBER = 2;
  private java.lang.String buyDate_;
  /**
   * <code>string buyDate = 2;</code>
   * @return The buyDate.
   */
  @java.lang.Override
  public java.lang.String getBuyDate() {
    return buyDate_;
  }
  /**
   * <code>string buyDate = 2;</code>
   * @return The bytes for buyDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBuyDateBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(buyDate_);
  }
  /**
   * <code>string buyDate = 2;</code>
   * @param value The buyDate to set.
   */
  private void setBuyDate(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    buyDate_ = value;
  }
  /**
   * <code>string buyDate = 2;</code>
   */
  private void clearBuyDate() {
    
    buyDate_ = getDefaultInstance().getBuyDate();
  }
  /**
   * <code>string buyDate = 2;</code>
   * @param value The bytes for buyDate to set.
   */
  private void setBuyDateBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    buyDate_ = value.toStringUtf8();
    
  }

  public static final int RESID_FIELD_NUMBER = 3;
  private java.lang.String resID_;
  /**
   * <code>string resID = 3;</code>
   * @return The resID.
   */
  @java.lang.Override
  public java.lang.String getResID() {
    return resID_;
  }
  /**
   * <code>string resID = 3;</code>
   * @return The bytes for resID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(resID_);
  }
  /**
   * <code>string resID = 3;</code>
   * @param value The resID to set.
   */
  private void setResID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    resID_ = value;
  }
  /**
   * <code>string resID = 3;</code>
   */
  private void clearResID() {
    
    resID_ = getDefaultInstance().getResID();
  }
  /**
   * <code>string resID = 3;</code>
   * @param value The bytes for resID to set.
   */
  private void setResIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    resID_ = value.toStringUtf8();
    
  }

  public static final int FOODLIST_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<com.example.foodzoneclient.protocols.Food> foodList_;
  /**
   * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.foodzoneclient.protocols.Food> getFoodListList() {
    return foodList_;
  }
  /**
   * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
   */
  public java.util.List<? extends com.example.foodzoneclient.protocols.FoodOrBuilder> 
      getFoodListOrBuilderList() {
    return foodList_;
  }
  /**
   * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
   */
  @java.lang.Override
  public int getFoodListCount() {
    return foodList_.size();
  }
  /**
   * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
   */
  @java.lang.Override
  public com.example.foodzoneclient.protocols.Food getFoodList(int index) {
    return foodList_.get(index);
  }
  /**
   * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
   */
  public com.example.foodzoneclient.protocols.FoodOrBuilder getFoodListOrBuilder(
      int index) {
    return foodList_.get(index);
  }
  private void ensureFoodListIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.example.foodzoneclient.protocols.Food> tmp = foodList_;
    if (!tmp.isModifiable()) {
      foodList_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
   */
  private void setFoodList(
      int index, com.example.foodzoneclient.protocols.Food value) {
    value.getClass();
  ensureFoodListIsMutable();
    foodList_.set(index, value);
  }
  /**
   * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
   */
  private void addFoodList(com.example.foodzoneclient.protocols.Food value) {
    value.getClass();
  ensureFoodListIsMutable();
    foodList_.add(value);
  }
  /**
   * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
   */
  private void addFoodList(
      int index, com.example.foodzoneclient.protocols.Food value) {
    value.getClass();
  ensureFoodListIsMutable();
    foodList_.add(index, value);
  }
  /**
   * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
   */
  private void addAllFoodList(
      java.lang.Iterable<? extends com.example.foodzoneclient.protocols.Food> values) {
    ensureFoodListIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, foodList_);
  }
  /**
   * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
   */
  private void clearFoodList() {
    foodList_ = emptyProtobufList();
  }
  /**
   * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
   */
  private void removeFoodList(int index) {
    ensureFoodListIsMutable();
    foodList_.remove(index);
  }

  public static com.example.foodzoneclient.protocols.Order parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.Order parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.foodzoneclient.protocols.Order parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.foodzoneclient.protocols.Order prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code foodzone_protocols.Order}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.foodzoneclient.protocols.Order, Builder> implements
      // @@protoc_insertion_point(builder_implements:foodzone_protocols.Order)
      com.example.foodzoneclient.protocols.OrderOrBuilder {
    // Construct using com.example.foodzoneclient.protocols.Order.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>string username = 1;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>string buyDate = 2;</code>
     * @return The buyDate.
     */
    @java.lang.Override
    public java.lang.String getBuyDate() {
      return instance.getBuyDate();
    }
    /**
     * <code>string buyDate = 2;</code>
     * @return The bytes for buyDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBuyDateBytes() {
      return instance.getBuyDateBytes();
    }
    /**
     * <code>string buyDate = 2;</code>
     * @param value The buyDate to set.
     * @return This builder for chaining.
     */
    public Builder setBuyDate(
        java.lang.String value) {
      copyOnWrite();
      instance.setBuyDate(value);
      return this;
    }
    /**
     * <code>string buyDate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuyDate() {
      copyOnWrite();
      instance.clearBuyDate();
      return this;
    }
    /**
     * <code>string buyDate = 2;</code>
     * @param value The bytes for buyDate to set.
     * @return This builder for chaining.
     */
    public Builder setBuyDateBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBuyDateBytes(value);
      return this;
    }

    /**
     * <code>string resID = 3;</code>
     * @return The resID.
     */
    @java.lang.Override
    public java.lang.String getResID() {
      return instance.getResID();
    }
    /**
     * <code>string resID = 3;</code>
     * @return The bytes for resID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResIDBytes() {
      return instance.getResIDBytes();
    }
    /**
     * <code>string resID = 3;</code>
     * @param value The resID to set.
     * @return This builder for chaining.
     */
    public Builder setResID(
        java.lang.String value) {
      copyOnWrite();
      instance.setResID(value);
      return this;
    }
    /**
     * <code>string resID = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearResID() {
      copyOnWrite();
      instance.clearResID();
      return this;
    }
    /**
     * <code>string resID = 3;</code>
     * @param value The bytes for resID to set.
     * @return This builder for chaining.
     */
    public Builder setResIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setResIDBytes(value);
      return this;
    }

    /**
     * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.foodzoneclient.protocols.Food> getFoodListList() {
      return java.util.Collections.unmodifiableList(
          instance.getFoodListList());
    }
    /**
     * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
     */
    @java.lang.Override
    public int getFoodListCount() {
      return instance.getFoodListCount();
    }/**
     * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
     */
    @java.lang.Override
    public com.example.foodzoneclient.protocols.Food getFoodList(int index) {
      return instance.getFoodList(index);
    }
    /**
     * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
     */
    public Builder setFoodList(
        int index, com.example.foodzoneclient.protocols.Food value) {
      copyOnWrite();
      instance.setFoodList(index, value);
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
     */
    public Builder setFoodList(
        int index, com.example.foodzoneclient.protocols.Food.Builder builderForValue) {
      copyOnWrite();
      instance.setFoodList(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
     */
    public Builder addFoodList(com.example.foodzoneclient.protocols.Food value) {
      copyOnWrite();
      instance.addFoodList(value);
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
     */
    public Builder addFoodList(
        int index, com.example.foodzoneclient.protocols.Food value) {
      copyOnWrite();
      instance.addFoodList(index, value);
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
     */
    public Builder addFoodList(
        com.example.foodzoneclient.protocols.Food.Builder builderForValue) {
      copyOnWrite();
      instance.addFoodList(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
     */
    public Builder addFoodList(
        int index, com.example.foodzoneclient.protocols.Food.Builder builderForValue) {
      copyOnWrite();
      instance.addFoodList(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
     */
    public Builder addAllFoodList(
        java.lang.Iterable<? extends com.example.foodzoneclient.protocols.Food> values) {
      copyOnWrite();
      instance.addAllFoodList(values);
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
     */
    public Builder clearFoodList() {
      copyOnWrite();
      instance.clearFoodList();
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Food foodList = 4;</code>
     */
    public Builder removeFoodList(int index) {
      copyOnWrite();
      instance.removeFoodList(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:foodzone_protocols.Order)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.foodzoneclient.protocols.Order();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "username_",
            "buyDate_",
            "resID_",
            "foodList_",
            com.example.foodzoneclient.protocols.Food.class,
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0001\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.foodzoneclient.protocols.Order> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.foodzoneclient.protocols.Order.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.foodzoneclient.protocols.Order>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:foodzone_protocols.Order)
  private static final com.example.foodzoneclient.protocols.Order DEFAULT_INSTANCE;
  static {
    Order defaultInstance = new Order();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Order.class, defaultInstance);
  }

  public static com.example.foodzoneclient.protocols.Order getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Order> PARSER;

  public static com.google.protobuf.Parser<Order> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

