// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.foodzoneclient.protocols;

/**
 * Protobuf type {@code foodzone_protocols.Order}
 */
public  final class Order extends
    com.google.protobuf.GeneratedMessageLite<
        Order, Order.Builder> implements
    // @@protoc_insertion_point(message_implements:foodzone_protocols.Order)
    OrderOrBuilder {
  private Order() {
    date_ = "";
    desc_ = "";
    state_ = "";
    recipientName_ = "";
  }
  public static final int DATE_FIELD_NUMBER = 1;
  private java.lang.String date_;
  /**
   * <code>string date = 1;</code>
   * @return The date.
   */
  @java.lang.Override
  public java.lang.String getDate() {
    return date_;
  }
  /**
   * <code>string date = 1;</code>
   * @return The bytes for date.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(date_);
  }
  /**
   * <code>string date = 1;</code>
   * @param value The date to set.
   */
  private void setDate(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    date_ = value;
  }
  /**
   * <code>string date = 1;</code>
   */
  private void clearDate() {
    
    date_ = getDefaultInstance().getDate();
  }
  /**
   * <code>string date = 1;</code>
   * @param value The bytes for date to set.
   */
  private void setDateBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    date_ = value.toStringUtf8();
    
  }

  public static final int DESC_FIELD_NUMBER = 2;
  private java.lang.String desc_;
  /**
   * <code>string desc = 2;</code>
   * @return The desc.
   */
  @java.lang.Override
  public java.lang.String getDesc() {
    return desc_;
  }
  /**
   * <code>string desc = 2;</code>
   * @return The bytes for desc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(desc_);
  }
  /**
   * <code>string desc = 2;</code>
   * @param value The desc to set.
   */
  private void setDesc(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    desc_ = value;
  }
  /**
   * <code>string desc = 2;</code>
   */
  private void clearDesc() {
    
    desc_ = getDefaultInstance().getDesc();
  }
  /**
   * <code>string desc = 2;</code>
   * @param value The bytes for desc to set.
   */
  private void setDescBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    desc_ = value.toStringUtf8();
    
  }

  public static final int STATE_FIELD_NUMBER = 3;
  private java.lang.String state_;
  /**
   * <code>string state = 3;</code>
   * @return The state.
   */
  @java.lang.Override
  public java.lang.String getState() {
    return state_;
  }
  /**
   * <code>string state = 3;</code>
   * @return The bytes for state.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStateBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(state_);
  }
  /**
   * <code>string state = 3;</code>
   * @param value The state to set.
   */
  private void setState(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    state_ = value;
  }
  /**
   * <code>string state = 3;</code>
   */
  private void clearState() {
    
    state_ = getDefaultInstance().getState();
  }
  /**
   * <code>string state = 3;</code>
   * @param value The bytes for state to set.
   */
  private void setStateBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    state_ = value.toStringUtf8();
    
  }

  public static final int RECIPIENTNAME_FIELD_NUMBER = 4;
  private java.lang.String recipientName_;
  /**
   * <code>string recipientName = 4;</code>
   * @return The recipientName.
   */
  @java.lang.Override
  public java.lang.String getRecipientName() {
    return recipientName_;
  }
  /**
   * <code>string recipientName = 4;</code>
   * @return The bytes for recipientName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecipientNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(recipientName_);
  }
  /**
   * <code>string recipientName = 4;</code>
   * @param value The recipientName to set.
   */
  private void setRecipientName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    recipientName_ = value;
  }
  /**
   * <code>string recipientName = 4;</code>
   */
  private void clearRecipientName() {
    
    recipientName_ = getDefaultInstance().getRecipientName();
  }
  /**
   * <code>string recipientName = 4;</code>
   * @param value The bytes for recipientName to set.
   */
  private void setRecipientNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    recipientName_ = value.toStringUtf8();
    
  }

  public static final int PRICE_FIELD_NUMBER = 5;
  private int price_;
  /**
   * <code>int32 price = 5;</code>
   * @return The price.
   */
  @java.lang.Override
  public int getPrice() {
    return price_;
  }
  /**
   * <code>int32 price = 5;</code>
   * @param value The price to set.
   */
  private void setPrice(int value) {
    
    price_ = value;
  }
  /**
   * <code>int32 price = 5;</code>
   */
  private void clearPrice() {
    
    price_ = 0;
  }

  public static com.example.foodzoneclient.protocols.Order parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.Order parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.foodzoneclient.protocols.Order parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.foodzoneclient.protocols.Order parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.foodzoneclient.protocols.Order prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code foodzone_protocols.Order}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.foodzoneclient.protocols.Order, Builder> implements
      // @@protoc_insertion_point(builder_implements:foodzone_protocols.Order)
      com.example.foodzoneclient.protocols.OrderOrBuilder {
    // Construct using com.example.foodzoneclient.protocols.Order.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      return instance.getDate();
    }
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      return instance.getDateBytes();
    }
    /**
     * <code>string date = 1;</code>
     * @param value The date to set.
     * @return This builder for chaining.
     */
    public Builder setDate(
        java.lang.String value) {
      copyOnWrite();
      instance.setDate(value);
      return this;
    }
    /**
     * <code>string date = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDate() {
      copyOnWrite();
      instance.clearDate();
      return this;
    }
    /**
     * <code>string date = 1;</code>
     * @param value The bytes for date to set.
     * @return This builder for chaining.
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDateBytes(value);
      return this;
    }

    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    @java.lang.Override
    public java.lang.String getDesc() {
      return instance.getDesc();
    }
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescBytes() {
      return instance.getDescBytes();
    }
    /**
     * <code>string desc = 2;</code>
     * @param value The desc to set.
     * @return This builder for chaining.
     */
    public Builder setDesc(
        java.lang.String value) {
      copyOnWrite();
      instance.setDesc(value);
      return this;
    }
    /**
     * <code>string desc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesc() {
      copyOnWrite();
      instance.clearDesc();
      return this;
    }
    /**
     * <code>string desc = 2;</code>
     * @param value The bytes for desc to set.
     * @return This builder for chaining.
     */
    public Builder setDescBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescBytes(value);
      return this;
    }

    /**
     * <code>string state = 3;</code>
     * @return The state.
     */
    @java.lang.Override
    public java.lang.String getState() {
      return instance.getState();
    }
    /**
     * <code>string state = 3;</code>
     * @return The bytes for state.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStateBytes() {
      return instance.getStateBytes();
    }
    /**
     * <code>string state = 3;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(
        java.lang.String value) {
      copyOnWrite();
      instance.setState(value);
      return this;
    }
    /**
     * <code>string state = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }
    /**
     * <code>string state = 3;</code>
     * @param value The bytes for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStateBytes(value);
      return this;
    }

    /**
     * <code>string recipientName = 4;</code>
     * @return The recipientName.
     */
    @java.lang.Override
    public java.lang.String getRecipientName() {
      return instance.getRecipientName();
    }
    /**
     * <code>string recipientName = 4;</code>
     * @return The bytes for recipientName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRecipientNameBytes() {
      return instance.getRecipientNameBytes();
    }
    /**
     * <code>string recipientName = 4;</code>
     * @param value The recipientName to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientName(
        java.lang.String value) {
      copyOnWrite();
      instance.setRecipientName(value);
      return this;
    }
    /**
     * <code>string recipientName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipientName() {
      copyOnWrite();
      instance.clearRecipientName();
      return this;
    }
    /**
     * <code>string recipientName = 4;</code>
     * @param value The bytes for recipientName to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRecipientNameBytes(value);
      return this;
    }

    /**
     * <code>int32 price = 5;</code>
     * @return The price.
     */
    @java.lang.Override
    public int getPrice() {
      return instance.getPrice();
    }
    /**
     * <code>int32 price = 5;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(int value) {
      copyOnWrite();
      instance.setPrice(value);
      return this;
    }
    /**
     * <code>int32 price = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      copyOnWrite();
      instance.clearPrice();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:foodzone_protocols.Order)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.foodzoneclient.protocols.Order();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "date_",
            "desc_",
            "state_",
            "recipientName_",
            "price_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.foodzoneclient.protocols.Order> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.foodzoneclient.protocols.Order.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.foodzoneclient.protocols.Order>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:foodzone_protocols.Order)
  private static final com.example.foodzoneclient.protocols.Order DEFAULT_INSTANCE;
  static {
    Order defaultInstance = new Order();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Order.class, defaultInstance);
  }

  public static com.example.foodzoneclient.protocols.Order getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Order> PARSER;

  public static com.google.protobuf.Parser<Order> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

