// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.foodzoneclient.protocols;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodzone_protocols.RegisterRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string fullname = 3;</code>
   * @return The fullname.
   */
  java.lang.String getFullname();
  /**
   * <code>string fullname = 3;</code>
   * @return The bytes for fullname.
   */
  com.google.protobuf.ByteString
      getFullnameBytes();

  /**
   * <code>string id = 4;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 4;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string address = 5;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 5;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string phone = 6;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 6;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();
}
