// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.foodzoneclient.protocols;

public interface RestaurantListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodzone_protocols.RestaurantListRequest)
    com.google.protobuf.MessageLiteOrBuilder {
}
