// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.foodzoneclient.protocols;

public interface ServerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodzone_protocols.ServerMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
   * @return Whether the loginResponse field is set.
   */
  boolean hasLoginResponse();
  /**
   * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
   * @return The loginResponse.
   */
  com.example.foodzoneclient.protocols.LoginResponse getLoginResponse();

  /**
   * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
   * @return Whether the registerResponse field is set.
   */
  boolean hasRegisterResponse();
  /**
   * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
   * @return The registerResponse.
   */
  com.example.foodzoneclient.protocols.RegisterResponse getRegisterResponse();

  public com.example.foodzoneclient.protocols.ServerMessage.ResponsesCase getResponsesCase();
}
