// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.foodzoneclient.protocols;

public interface ServerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodzone_protocols.ServerMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
   * @return Whether the loginResponse field is set.
   */
  boolean hasLoginResponse();
  /**
   * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
   * @return The loginResponse.
   */
  com.example.foodzoneclient.protocols.LoginResponse getLoginResponse();

  /**
   * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
   * @return Whether the registerResponse field is set.
   */
  boolean hasRegisterResponse();
  /**
   * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
   * @return The registerResponse.
   */
  com.example.foodzoneclient.protocols.RegisterResponse getRegisterResponse();

  /**
   * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
   * @return Whether the updateInfoResponse field is set.
   */
  boolean hasUpdateInfoResponse();
  /**
   * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
   * @return The updateInfoResponse.
   */
  com.example.foodzoneclient.protocols.UpdateInfoResponse getUpdateInfoResponse();

  /**
   * <code>.foodzone_protocols.UpdatePasswordResponse updatePasswordResponse = 5;</code>
   * @return Whether the updatePasswordResponse field is set.
   */
  boolean hasUpdatePasswordResponse();
  /**
   * <code>.foodzone_protocols.UpdatePasswordResponse updatePasswordResponse = 5;</code>
   * @return The updatePasswordResponse.
   */
  com.example.foodzoneclient.protocols.UpdatePasswordResponse getUpdatePasswordResponse();

  /**
   * <code>.foodzone_protocols.SubmitOrderResponse submitOrderResponse = 6;</code>
   * @return Whether the submitOrderResponse field is set.
   */
  boolean hasSubmitOrderResponse();
  /**
   * <code>.foodzone_protocols.SubmitOrderResponse submitOrderResponse = 6;</code>
   * @return The submitOrderResponse.
   */
  com.example.foodzoneclient.protocols.SubmitOrderResponse getSubmitOrderResponse();

  public com.example.foodzoneclient.protocols.ServerMessage.ResponsesCase getResponsesCase();
}
