// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.example.foodzoneclient.protocols;

/**
 * Protobuf type {@code foodzone_protocols.SubmitOrder}
 */
public  final class SubmitOrder extends
    com.google.protobuf.GeneratedMessageLite<
        SubmitOrder, SubmitOrder.Builder> implements
    // @@protoc_insertion_point(message_implements:foodzone_protocols.SubmitOrder)
    SubmitOrderOrBuilder {
  private SubmitOrder() {
    username_ = "";
    datetime_ = "";
    mealID_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    mealQuantity_ = emptyIntList();
  }
  public static final int USERNAME_FIELD_NUMBER = 1;
  private java.lang.String username_;
  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>string username = 1;</code>
   * @param value The username to set.
   */
  private void setUsername(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    username_ = value;
  }
  /**
   * <code>string username = 1;</code>
   */
  private void clearUsername() {
    
    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>string username = 1;</code>
   * @param value The bytes for username to set.
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    username_ = value.toStringUtf8();
    
  }

  public static final int DATETIME_FIELD_NUMBER = 2;
  private java.lang.String datetime_;
  /**
   * <code>string datetime = 2;</code>
   * @return The datetime.
   */
  @java.lang.Override
  public java.lang.String getDatetime() {
    return datetime_;
  }
  /**
   * <code>string datetime = 2;</code>
   * @return The bytes for datetime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDatetimeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(datetime_);
  }
  /**
   * <code>string datetime = 2;</code>
   * @param value The datetime to set.
   */
  private void setDatetime(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    datetime_ = value;
  }
  /**
   * <code>string datetime = 2;</code>
   */
  private void clearDatetime() {
    
    datetime_ = getDefaultInstance().getDatetime();
  }
  /**
   * <code>string datetime = 2;</code>
   * @param value The bytes for datetime to set.
   */
  private void setDatetimeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    datetime_ = value.toStringUtf8();
    
  }

  public static final int MEALID_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> mealID_;
  /**
   * <code>repeated string mealID = 3;</code>
   * @return A list containing the mealID.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getMealIDList() {
    return mealID_;
  }
  /**
   * <code>repeated string mealID = 3;</code>
   * @return The count of mealID.
   */
  @java.lang.Override
  public int getMealIDCount() {
    return mealID_.size();
  }
  /**
   * <code>repeated string mealID = 3;</code>
   * @param index The index of the element to return.
   * @return The mealID at the given index.
   */
  @java.lang.Override
  public java.lang.String getMealID(int index) {
    return mealID_.get(index);
  }
  /**
   * <code>repeated string mealID = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the mealID at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMealIDBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        mealID_.get(index));
  }
  private void ensureMealIDIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        mealID_;  if (!tmp.isModifiable()) {
      mealID_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string mealID = 3;</code>
   * @param index The index to set the value at.
   * @param value The mealID to set.
   */
  private void setMealID(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureMealIDIsMutable();
    mealID_.set(index, value);
  }
  /**
   * <code>repeated string mealID = 3;</code>
   * @param value The mealID to add.
   */
  private void addMealID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureMealIDIsMutable();
    mealID_.add(value);
  }
  /**
   * <code>repeated string mealID = 3;</code>
   * @param values The mealID to add.
   */
  private void addAllMealID(
      java.lang.Iterable<java.lang.String> values) {
    ensureMealIDIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, mealID_);
  }
  /**
   * <code>repeated string mealID = 3;</code>
   */
  private void clearMealID() {
    mealID_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string mealID = 3;</code>
   * @param value The bytes of the mealID to add.
   */
  private void addMealIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureMealIDIsMutable();
    mealID_.add(value.toStringUtf8());
  }

  public static final int MEALQUANTITY_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.IntList mealQuantity_;
  /**
   * <code>repeated int32 mealQuantity = 4;</code>
   * @return A list containing the mealQuantity.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getMealQuantityList() {
    return mealQuantity_;
  }
  /**
   * <code>repeated int32 mealQuantity = 4;</code>
   * @return The count of mealQuantity.
   */
  @java.lang.Override
  public int getMealQuantityCount() {
    return mealQuantity_.size();
  }
  /**
   * <code>repeated int32 mealQuantity = 4;</code>
   * @param index The index of the element to return.
   * @return The mealQuantity at the given index.
   */
  @java.lang.Override
  public int getMealQuantity(int index) {
    return mealQuantity_.getInt(index);
  }
  private int mealQuantityMemoizedSerializedSize = -1;
  private void ensureMealQuantityIsMutable() {
    com.google.protobuf.Internal.IntList tmp = mealQuantity_;
    if (!tmp.isModifiable()) {
      mealQuantity_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated int32 mealQuantity = 4;</code>
   * @param index The index to set the value at.
   * @param value The mealQuantity to set.
   */
  private void setMealQuantity(
      int index, int value) {
    ensureMealQuantityIsMutable();
    mealQuantity_.setInt(index, value);
  }
  /**
   * <code>repeated int32 mealQuantity = 4;</code>
   * @param value The mealQuantity to add.
   */
  private void addMealQuantity(int value) {
    ensureMealQuantityIsMutable();
    mealQuantity_.addInt(value);
  }
  /**
   * <code>repeated int32 mealQuantity = 4;</code>
   * @param values The mealQuantity to add.
   */
  private void addAllMealQuantity(
      java.lang.Iterable<? extends java.lang.Integer> values) {
    ensureMealQuantityIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, mealQuantity_);
  }
  /**
   * <code>repeated int32 mealQuantity = 4;</code>
   */
  private void clearMealQuantity() {
    mealQuantity_ = emptyIntList();
  }

  public static com.example.foodzoneclient.protocols.SubmitOrder parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.foodzoneclient.protocols.SubmitOrder parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.SubmitOrder parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.foodzoneclient.protocols.SubmitOrder parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.SubmitOrder parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.foodzoneclient.protocols.SubmitOrder parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.SubmitOrder parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.foodzoneclient.protocols.SubmitOrder parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.SubmitOrder parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.foodzoneclient.protocols.SubmitOrder parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.foodzoneclient.protocols.SubmitOrder parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.foodzoneclient.protocols.SubmitOrder parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.foodzoneclient.protocols.SubmitOrder prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code foodzone_protocols.SubmitOrder}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.foodzoneclient.protocols.SubmitOrder, Builder> implements
      // @@protoc_insertion_point(builder_implements:foodzone_protocols.SubmitOrder)
      com.example.foodzoneclient.protocols.SubmitOrderOrBuilder {
    // Construct using com.example.foodzoneclient.protocols.SubmitOrder.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>string username = 1;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>string datetime = 2;</code>
     * @return The datetime.
     */
    @java.lang.Override
    public java.lang.String getDatetime() {
      return instance.getDatetime();
    }
    /**
     * <code>string datetime = 2;</code>
     * @return The bytes for datetime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDatetimeBytes() {
      return instance.getDatetimeBytes();
    }
    /**
     * <code>string datetime = 2;</code>
     * @param value The datetime to set.
     * @return This builder for chaining.
     */
    public Builder setDatetime(
        java.lang.String value) {
      copyOnWrite();
      instance.setDatetime(value);
      return this;
    }
    /**
     * <code>string datetime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDatetime() {
      copyOnWrite();
      instance.clearDatetime();
      return this;
    }
    /**
     * <code>string datetime = 2;</code>
     * @param value The bytes for datetime to set.
     * @return This builder for chaining.
     */
    public Builder setDatetimeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDatetimeBytes(value);
      return this;
    }

    /**
     * <code>repeated string mealID = 3;</code>
     * @return A list containing the mealID.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getMealIDList() {
      return java.util.Collections.unmodifiableList(
          instance.getMealIDList());
    }
    /**
     * <code>repeated string mealID = 3;</code>
     * @return The count of mealID.
     */
    @java.lang.Override
    public int getMealIDCount() {
      return instance.getMealIDCount();
    }
    /**
     * <code>repeated string mealID = 3;</code>
     * @param index The index of the element to return.
     * @return The mealID at the given index.
     */
    @java.lang.Override
    public java.lang.String getMealID(int index) {
      return instance.getMealID(index);
    }
    /**
     * <code>repeated string mealID = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the mealID at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMealIDBytes(int index) {
      return instance.getMealIDBytes(index);
    }
    /**
     * <code>repeated string mealID = 3;</code>
     * @param index The index to set the value at.
     * @param value The mealID to set.
     * @return This builder for chaining.
     */
    public Builder setMealID(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setMealID(index, value);
      return this;
    }
    /**
     * <code>repeated string mealID = 3;</code>
     * @param value The mealID to add.
     * @return This builder for chaining.
     */
    public Builder addMealID(
        java.lang.String value) {
      copyOnWrite();
      instance.addMealID(value);
      return this;
    }
    /**
     * <code>repeated string mealID = 3;</code>
     * @param values The mealID to add.
     * @return This builder for chaining.
     */
    public Builder addAllMealID(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllMealID(values);
      return this;
    }
    /**
     * <code>repeated string mealID = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMealID() {
      copyOnWrite();
      instance.clearMealID();
      return this;
    }
    /**
     * <code>repeated string mealID = 3;</code>
     * @param value The bytes of the mealID to add.
     * @return This builder for chaining.
     */
    public Builder addMealIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addMealIDBytes(value);
      return this;
    }

    /**
     * <code>repeated int32 mealQuantity = 4;</code>
     * @return A list containing the mealQuantity.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getMealQuantityList() {
      return java.util.Collections.unmodifiableList(
          instance.getMealQuantityList());
    }
    /**
     * <code>repeated int32 mealQuantity = 4;</code>
     * @return The count of mealQuantity.
     */
    @java.lang.Override
    public int getMealQuantityCount() {
      return instance.getMealQuantityCount();
    }
    /**
     * <code>repeated int32 mealQuantity = 4;</code>
     * @param index The index of the element to return.
     * @return The mealQuantity at the given index.
     */
    @java.lang.Override
    public int getMealQuantity(int index) {
      return instance.getMealQuantity(index);
    }
    /**
     * <code>repeated int32 mealQuantity = 4;</code>
     * @param value The mealQuantity to set.
     * @return This builder for chaining.
     */
    public Builder setMealQuantity(
        int index, int value) {
      copyOnWrite();
      instance.setMealQuantity(index, value);
      return this;
    }
    /**
     * <code>repeated int32 mealQuantity = 4;</code>
     * @param value The mealQuantity to add.
     * @return This builder for chaining.
     */
    public Builder addMealQuantity(int value) {
      copyOnWrite();
      instance.addMealQuantity(value);
      return this;
    }
    /**
     * <code>repeated int32 mealQuantity = 4;</code>
     * @param values The mealQuantity to add.
     * @return This builder for chaining.
     */
    public Builder addAllMealQuantity(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      copyOnWrite();
      instance.addAllMealQuantity(values);
      return this;
    }
    /**
     * <code>repeated int32 mealQuantity = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMealQuantity() {
      copyOnWrite();
      instance.clearMealQuantity();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:foodzone_protocols.SubmitOrder)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.foodzoneclient.protocols.SubmitOrder();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "username_",
            "datetime_",
            "mealID_",
            "mealQuantity_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0002\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u021a\u0004\'";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.foodzoneclient.protocols.SubmitOrder> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.foodzoneclient.protocols.SubmitOrder.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.foodzoneclient.protocols.SubmitOrder>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:foodzone_protocols.SubmitOrder)
  private static final com.example.foodzoneclient.protocols.SubmitOrder DEFAULT_INSTANCE;
  static {
    SubmitOrder defaultInstance = new SubmitOrder();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SubmitOrder.class, defaultInstance);
  }

  public static com.example.foodzoneclient.protocols.SubmitOrder getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SubmitOrder> PARSER;

  public static com.google.protobuf.Parser<SubmitOrder> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

