// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.fz.foodzoneserver.protocols;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodzone_protocols.ClientMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>.foodzone_protocols.LoginRequest loginRequest = 2;</code>
   * @return Whether the loginRequest field is set.
   */
  boolean hasLoginRequest();
  /**
   * <code>.foodzone_protocols.LoginRequest loginRequest = 2;</code>
   * @return The loginRequest.
   */
  com.fz.foodzoneserver.protocols.LoginRequest getLoginRequest();
  /**
   * <code>.foodzone_protocols.LoginRequest loginRequest = 2;</code>
   */
  com.fz.foodzoneserver.protocols.LoginRequestOrBuilder getLoginRequestOrBuilder();

  /**
   * <code>.foodzone_protocols.RegisterRequest registerRequest = 3;</code>
   * @return Whether the registerRequest field is set.
   */
  boolean hasRegisterRequest();
  /**
   * <code>.foodzone_protocols.RegisterRequest registerRequest = 3;</code>
   * @return The registerRequest.
   */
  com.fz.foodzoneserver.protocols.RegisterRequest getRegisterRequest();
  /**
   * <code>.foodzone_protocols.RegisterRequest registerRequest = 3;</code>
   */
  com.fz.foodzoneserver.protocols.RegisterRequestOrBuilder getRegisterRequestOrBuilder();

  /**
   * <code>.foodzone_protocols.UserInfo updateInfoRequest = 4;</code>
   * @return Whether the updateInfoRequest field is set.
   */
  boolean hasUpdateInfoRequest();
  /**
   * <code>.foodzone_protocols.UserInfo updateInfoRequest = 4;</code>
   * @return The updateInfoRequest.
   */
  com.fz.foodzoneserver.protocols.UserInfo getUpdateInfoRequest();
  /**
   * <code>.foodzone_protocols.UserInfo updateInfoRequest = 4;</code>
   */
  com.fz.foodzoneserver.protocols.UserInfoOrBuilder getUpdateInfoRequestOrBuilder();

  /**
   * <code>.foodzone_protocols.UpdatePasswordRequest updatePasswordRequest = 5;</code>
   * @return Whether the updatePasswordRequest field is set.
   */
  boolean hasUpdatePasswordRequest();
  /**
   * <code>.foodzone_protocols.UpdatePasswordRequest updatePasswordRequest = 5;</code>
   * @return The updatePasswordRequest.
   */
  com.fz.foodzoneserver.protocols.UpdatePasswordRequest getUpdatePasswordRequest();
  /**
   * <code>.foodzone_protocols.UpdatePasswordRequest updatePasswordRequest = 5;</code>
   */
  com.fz.foodzoneserver.protocols.UpdatePasswordRequestOrBuilder getUpdatePasswordRequestOrBuilder();

  /**
   * <code>.foodzone_protocols.SubmitOrderRequest submitOrder = 6;</code>
   * @return Whether the submitOrder field is set.
   */
  boolean hasSubmitOrder();
  /**
   * <code>.foodzone_protocols.SubmitOrderRequest submitOrder = 6;</code>
   * @return The submitOrder.
   */
  com.fz.foodzoneserver.protocols.SubmitOrderRequest getSubmitOrder();
  /**
   * <code>.foodzone_protocols.SubmitOrderRequest submitOrder = 6;</code>
   */
  com.fz.foodzoneserver.protocols.SubmitOrderRequestOrBuilder getSubmitOrderOrBuilder();

  /**
   * <code>.foodzone_protocols.RestaurantListRequest restaurantListRequest = 7;</code>
   * @return Whether the restaurantListRequest field is set.
   */
  boolean hasRestaurantListRequest();
  /**
   * <code>.foodzone_protocols.RestaurantListRequest restaurantListRequest = 7;</code>
   * @return The restaurantListRequest.
   */
  com.fz.foodzoneserver.protocols.RestaurantListRequest getRestaurantListRequest();
  /**
   * <code>.foodzone_protocols.RestaurantListRequest restaurantListRequest = 7;</code>
   */
  com.fz.foodzoneserver.protocols.RestaurantListRequestOrBuilder getRestaurantListRequestOrBuilder();

  /**
   * <code>.foodzone_protocols.FoodListRequest foodListRequest = 8;</code>
   * @return Whether the foodListRequest field is set.
   */
  boolean hasFoodListRequest();
  /**
   * <code>.foodzone_protocols.FoodListRequest foodListRequest = 8;</code>
   * @return The foodListRequest.
   */
  com.fz.foodzoneserver.protocols.FoodListRequest getFoodListRequest();
  /**
   * <code>.foodzone_protocols.FoodListRequest foodListRequest = 8;</code>
   */
  com.fz.foodzoneserver.protocols.FoodListRequestOrBuilder getFoodListRequestOrBuilder();

  /**
   * <code>.foodzone_protocols.HistoryListRequest historyListRequest = 9;</code>
   * @return Whether the historyListRequest field is set.
   */
  boolean hasHistoryListRequest();
  /**
   * <code>.foodzone_protocols.HistoryListRequest historyListRequest = 9;</code>
   * @return The historyListRequest.
   */
  com.fz.foodzoneserver.protocols.HistoryListRequest getHistoryListRequest();
  /**
   * <code>.foodzone_protocols.HistoryListRequest historyListRequest = 9;</code>
   */
  com.fz.foodzoneserver.protocols.HistoryListRequestOrBuilder getHistoryListRequestOrBuilder();

  public com.fz.foodzoneserver.protocols.ClientMessage.RequestsCase getRequestsCase();
}
