// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.fz.foodzoneserver.protocols;

/**
 * Protobuf type {@code foodzone_protocols.FoodListResponse}
 */
public final class FoodListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:foodzone_protocols.FoodListResponse)
    FoodListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FoodListResponse.newBuilder() to construct.
  private FoodListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FoodListResponse() {
    result_ = "";
    food_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FoodListResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FoodListResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            result_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              food_ = new java.util.ArrayList<com.fz.foodzoneserver.protocols.FoodInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            food_.add(
                input.readMessage(com.fz.foodzoneserver.protocols.FoodInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        food_ = java.util.Collections.unmodifiableList(food_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fz.foodzoneserver.protocols.MessageWrapper.internal_static_foodzone_protocols_FoodListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fz.foodzoneserver.protocols.MessageWrapper.internal_static_foodzone_protocols_FoodListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fz.foodzoneserver.protocols.FoodListResponse.class, com.fz.foodzoneserver.protocols.FoodListResponse.Builder.class);
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  private volatile java.lang.Object result_;
  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  @java.lang.Override
  public java.lang.String getResult() {
    java.lang.Object ref = result_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      result_ = s;
      return s;
    }
  }
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResultBytes() {
    java.lang.Object ref = result_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      result_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FOOD_FIELD_NUMBER = 2;
  private java.util.List<com.fz.foodzoneserver.protocols.FoodInfo> food_;
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.fz.foodzoneserver.protocols.FoodInfo> getFoodList() {
    return food_;
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.fz.foodzoneserver.protocols.FoodInfoOrBuilder> 
      getFoodOrBuilderList() {
    return food_;
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  @java.lang.Override
  public int getFoodCount() {
    return food_.size();
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  @java.lang.Override
  public com.fz.foodzoneserver.protocols.FoodInfo getFood(int index) {
    return food_.get(index);
  }
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  @java.lang.Override
  public com.fz.foodzoneserver.protocols.FoodInfoOrBuilder getFoodOrBuilder(
      int index) {
    return food_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(result_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, result_);
    }
    for (int i = 0; i < food_.size(); i++) {
      output.writeMessage(2, food_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(result_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, result_);
    }
    for (int i = 0; i < food_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, food_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fz.foodzoneserver.protocols.FoodListResponse)) {
      return super.equals(obj);
    }
    com.fz.foodzoneserver.protocols.FoodListResponse other = (com.fz.foodzoneserver.protocols.FoodListResponse) obj;

    if (!getResult()
        .equals(other.getResult())) return false;
    if (!getFoodList()
        .equals(other.getFoodList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + getResult().hashCode();
    if (getFoodCount() > 0) {
      hash = (37 * hash) + FOOD_FIELD_NUMBER;
      hash = (53 * hash) + getFoodList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fz.foodzoneserver.protocols.FoodListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fz.foodzoneserver.protocols.FoodListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fz.foodzoneserver.protocols.FoodListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fz.foodzoneserver.protocols.FoodListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fz.foodzoneserver.protocols.FoodListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fz.foodzoneserver.protocols.FoodListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fz.foodzoneserver.protocols.FoodListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fz.foodzoneserver.protocols.FoodListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fz.foodzoneserver.protocols.FoodListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fz.foodzoneserver.protocols.FoodListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fz.foodzoneserver.protocols.FoodListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fz.foodzoneserver.protocols.FoodListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fz.foodzoneserver.protocols.FoodListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code foodzone_protocols.FoodListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:foodzone_protocols.FoodListResponse)
      com.fz.foodzoneserver.protocols.FoodListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fz.foodzoneserver.protocols.MessageWrapper.internal_static_foodzone_protocols_FoodListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fz.foodzoneserver.protocols.MessageWrapper.internal_static_foodzone_protocols_FoodListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fz.foodzoneserver.protocols.FoodListResponse.class, com.fz.foodzoneserver.protocols.FoodListResponse.Builder.class);
    }

    // Construct using com.fz.foodzoneserver.protocols.FoodListResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFoodFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      result_ = "";

      if (foodBuilder_ == null) {
        food_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        foodBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fz.foodzoneserver.protocols.MessageWrapper.internal_static_foodzone_protocols_FoodListResponse_descriptor;
    }

    @java.lang.Override
    public com.fz.foodzoneserver.protocols.FoodListResponse getDefaultInstanceForType() {
      return com.fz.foodzoneserver.protocols.FoodListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.fz.foodzoneserver.protocols.FoodListResponse build() {
      com.fz.foodzoneserver.protocols.FoodListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fz.foodzoneserver.protocols.FoodListResponse buildPartial() {
      com.fz.foodzoneserver.protocols.FoodListResponse result = new com.fz.foodzoneserver.protocols.FoodListResponse(this);
      int from_bitField0_ = bitField0_;
      result.result_ = result_;
      if (foodBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          food_ = java.util.Collections.unmodifiableList(food_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.food_ = food_;
      } else {
        result.food_ = foodBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fz.foodzoneserver.protocols.FoodListResponse) {
        return mergeFrom((com.fz.foodzoneserver.protocols.FoodListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fz.foodzoneserver.protocols.FoodListResponse other) {
      if (other == com.fz.foodzoneserver.protocols.FoodListResponse.getDefaultInstance()) return this;
      if (!other.getResult().isEmpty()) {
        result_ = other.result_;
        onChanged();
      }
      if (foodBuilder_ == null) {
        if (!other.food_.isEmpty()) {
          if (food_.isEmpty()) {
            food_ = other.food_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFoodIsMutable();
            food_.addAll(other.food_);
          }
          onChanged();
        }
      } else {
        if (!other.food_.isEmpty()) {
          if (foodBuilder_.isEmpty()) {
            foodBuilder_.dispose();
            foodBuilder_ = null;
            food_ = other.food_;
            bitField0_ = (bitField0_ & ~0x00000001);
            foodBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFoodFieldBuilder() : null;
          } else {
            foodBuilder_.addAllMessages(other.food_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fz.foodzoneserver.protocols.FoodListResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fz.foodzoneserver.protocols.FoodListResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object result_ = "";
    /**
     * <code>string result = 1;</code>
     * @return The result.
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string result = 1;</code>
     * @return The bytes for result.
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string result = 1;</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string result = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      
      result_ = getDefaultInstance().getResult();
      onChanged();
      return this;
    }
    /**
     * <code>string result = 1;</code>
     * @param value The bytes for result to set.
     * @return This builder for chaining.
     */
    public Builder setResultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      result_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.fz.foodzoneserver.protocols.FoodInfo> food_ =
      java.util.Collections.emptyList();
    private void ensureFoodIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        food_ = new java.util.ArrayList<com.fz.foodzoneserver.protocols.FoodInfo>(food_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.fz.foodzoneserver.protocols.FoodInfo, com.fz.foodzoneserver.protocols.FoodInfo.Builder, com.fz.foodzoneserver.protocols.FoodInfoOrBuilder> foodBuilder_;

    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public java.util.List<com.fz.foodzoneserver.protocols.FoodInfo> getFoodList() {
      if (foodBuilder_ == null) {
        return java.util.Collections.unmodifiableList(food_);
      } else {
        return foodBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public int getFoodCount() {
      if (foodBuilder_ == null) {
        return food_.size();
      } else {
        return foodBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public com.fz.foodzoneserver.protocols.FoodInfo getFood(int index) {
      if (foodBuilder_ == null) {
        return food_.get(index);
      } else {
        return foodBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder setFood(
        int index, com.fz.foodzoneserver.protocols.FoodInfo value) {
      if (foodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFoodIsMutable();
        food_.set(index, value);
        onChanged();
      } else {
        foodBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder setFood(
        int index, com.fz.foodzoneserver.protocols.FoodInfo.Builder builderForValue) {
      if (foodBuilder_ == null) {
        ensureFoodIsMutable();
        food_.set(index, builderForValue.build());
        onChanged();
      } else {
        foodBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder addFood(com.fz.foodzoneserver.protocols.FoodInfo value) {
      if (foodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFoodIsMutable();
        food_.add(value);
        onChanged();
      } else {
        foodBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder addFood(
        int index, com.fz.foodzoneserver.protocols.FoodInfo value) {
      if (foodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFoodIsMutable();
        food_.add(index, value);
        onChanged();
      } else {
        foodBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder addFood(
        com.fz.foodzoneserver.protocols.FoodInfo.Builder builderForValue) {
      if (foodBuilder_ == null) {
        ensureFoodIsMutable();
        food_.add(builderForValue.build());
        onChanged();
      } else {
        foodBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder addFood(
        int index, com.fz.foodzoneserver.protocols.FoodInfo.Builder builderForValue) {
      if (foodBuilder_ == null) {
        ensureFoodIsMutable();
        food_.add(index, builderForValue.build());
        onChanged();
      } else {
        foodBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder addAllFood(
        java.lang.Iterable<? extends com.fz.foodzoneserver.protocols.FoodInfo> values) {
      if (foodBuilder_ == null) {
        ensureFoodIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, food_);
        onChanged();
      } else {
        foodBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder clearFood() {
      if (foodBuilder_ == null) {
        food_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        foodBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public Builder removeFood(int index) {
      if (foodBuilder_ == null) {
        ensureFoodIsMutable();
        food_.remove(index);
        onChanged();
      } else {
        foodBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public com.fz.foodzoneserver.protocols.FoodInfo.Builder getFoodBuilder(
        int index) {
      return getFoodFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public com.fz.foodzoneserver.protocols.FoodInfoOrBuilder getFoodOrBuilder(
        int index) {
      if (foodBuilder_ == null) {
        return food_.get(index);  } else {
        return foodBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public java.util.List<? extends com.fz.foodzoneserver.protocols.FoodInfoOrBuilder> 
         getFoodOrBuilderList() {
      if (foodBuilder_ != null) {
        return foodBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(food_);
      }
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public com.fz.foodzoneserver.protocols.FoodInfo.Builder addFoodBuilder() {
      return getFoodFieldBuilder().addBuilder(
          com.fz.foodzoneserver.protocols.FoodInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public com.fz.foodzoneserver.protocols.FoodInfo.Builder addFoodBuilder(
        int index) {
      return getFoodFieldBuilder().addBuilder(
          index, com.fz.foodzoneserver.protocols.FoodInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
     */
    public java.util.List<com.fz.foodzoneserver.protocols.FoodInfo.Builder> 
         getFoodBuilderList() {
      return getFoodFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.fz.foodzoneserver.protocols.FoodInfo, com.fz.foodzoneserver.protocols.FoodInfo.Builder, com.fz.foodzoneserver.protocols.FoodInfoOrBuilder> 
        getFoodFieldBuilder() {
      if (foodBuilder_ == null) {
        foodBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.fz.foodzoneserver.protocols.FoodInfo, com.fz.foodzoneserver.protocols.FoodInfo.Builder, com.fz.foodzoneserver.protocols.FoodInfoOrBuilder>(
                food_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        food_ = null;
      }
      return foodBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:foodzone_protocols.FoodListResponse)
  }

  // @@protoc_insertion_point(class_scope:foodzone_protocols.FoodListResponse)
  private static final com.fz.foodzoneserver.protocols.FoodListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fz.foodzoneserver.protocols.FoodListResponse();
  }

  public static com.fz.foodzoneserver.protocols.FoodListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FoodListResponse>
      PARSER = new com.google.protobuf.AbstractParser<FoodListResponse>() {
    @java.lang.Override
    public FoodListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FoodListResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FoodListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FoodListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fz.foodzoneserver.protocols.FoodListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

