// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.fz.foodzoneserver.protocols;

public interface FoodInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodzone_protocols.FoodInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ID = 1;</code>
   * @return The iD.
   */
  java.lang.String getID();
  /**
   * <code>string ID = 1;</code>
   * @return The bytes for iD.
   */
  com.google.protobuf.ByteString
      getIDBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>int32 price = 4;</code>
   * @return The price.
   */
  int getPrice();

  /**
   * <code>string image = 5;</code>
   * @return The image.
   */
  java.lang.String getImage();
  /**
   * <code>string image = 5;</code>
   * @return The bytes for image.
   */
  com.google.protobuf.ByteString
      getImageBytes();
}
