// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.fz.foodzoneserver.protocols;

public interface FoodListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodzone_protocols.FoodListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  java.util.List<com.fz.foodzoneserver.protocols.FoodInfo> 
      getFoodList();
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  com.fz.foodzoneserver.protocols.FoodInfo getFood(int index);
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  int getFoodCount();
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  java.util.List<? extends com.fz.foodzoneserver.protocols.FoodInfoOrBuilder> 
      getFoodOrBuilderList();
  /**
   * <code>repeated .foodzone_protocols.FoodInfo food = 2;</code>
   */
  com.fz.foodzoneserver.protocols.FoodInfoOrBuilder getFoodOrBuilder(
      int index);
}
