// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.fz.foodzoneserver.protocols;

/**
 * Protobuf type {@code foodzone_protocols.HistoryListResponse}
 */
public final class HistoryListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:foodzone_protocols.HistoryListResponse)
    HistoryListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HistoryListResponse.newBuilder() to construct.
  private HistoryListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HistoryListResponse() {
    result_ = "";
    orderHistory_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HistoryListResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HistoryListResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            result_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              orderHistory_ = new java.util.ArrayList<com.fz.foodzoneserver.protocols.Order>();
              mutable_bitField0_ |= 0x00000001;
            }
            orderHistory_.add(
                input.readMessage(com.fz.foodzoneserver.protocols.Order.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        orderHistory_ = java.util.Collections.unmodifiableList(orderHistory_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fz.foodzoneserver.protocols.MessageWrapper.internal_static_foodzone_protocols_HistoryListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fz.foodzoneserver.protocols.MessageWrapper.internal_static_foodzone_protocols_HistoryListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fz.foodzoneserver.protocols.HistoryListResponse.class, com.fz.foodzoneserver.protocols.HistoryListResponse.Builder.class);
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  private volatile java.lang.Object result_;
  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  @java.lang.Override
  public java.lang.String getResult() {
    java.lang.Object ref = result_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      result_ = s;
      return s;
    }
  }
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResultBytes() {
    java.lang.Object ref = result_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      result_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDERHISTORY_FIELD_NUMBER = 2;
  private java.util.List<com.fz.foodzoneserver.protocols.Order> orderHistory_;
  /**
   * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.fz.foodzoneserver.protocols.Order> getOrderHistoryList() {
    return orderHistory_;
  }
  /**
   * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.fz.foodzoneserver.protocols.OrderOrBuilder> 
      getOrderHistoryOrBuilderList() {
    return orderHistory_;
  }
  /**
   * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
   */
  @java.lang.Override
  public int getOrderHistoryCount() {
    return orderHistory_.size();
  }
  /**
   * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
   */
  @java.lang.Override
  public com.fz.foodzoneserver.protocols.Order getOrderHistory(int index) {
    return orderHistory_.get(index);
  }
  /**
   * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
   */
  @java.lang.Override
  public com.fz.foodzoneserver.protocols.OrderOrBuilder getOrderHistoryOrBuilder(
      int index) {
    return orderHistory_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(result_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, result_);
    }
    for (int i = 0; i < orderHistory_.size(); i++) {
      output.writeMessage(2, orderHistory_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(result_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, result_);
    }
    for (int i = 0; i < orderHistory_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, orderHistory_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fz.foodzoneserver.protocols.HistoryListResponse)) {
      return super.equals(obj);
    }
    com.fz.foodzoneserver.protocols.HistoryListResponse other = (com.fz.foodzoneserver.protocols.HistoryListResponse) obj;

    if (!getResult()
        .equals(other.getResult())) return false;
    if (!getOrderHistoryList()
        .equals(other.getOrderHistoryList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + getResult().hashCode();
    if (getOrderHistoryCount() > 0) {
      hash = (37 * hash) + ORDERHISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getOrderHistoryList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fz.foodzoneserver.protocols.HistoryListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fz.foodzoneserver.protocols.HistoryListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fz.foodzoneserver.protocols.HistoryListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fz.foodzoneserver.protocols.HistoryListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fz.foodzoneserver.protocols.HistoryListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fz.foodzoneserver.protocols.HistoryListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fz.foodzoneserver.protocols.HistoryListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fz.foodzoneserver.protocols.HistoryListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fz.foodzoneserver.protocols.HistoryListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fz.foodzoneserver.protocols.HistoryListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fz.foodzoneserver.protocols.HistoryListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fz.foodzoneserver.protocols.HistoryListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fz.foodzoneserver.protocols.HistoryListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code foodzone_protocols.HistoryListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:foodzone_protocols.HistoryListResponse)
      com.fz.foodzoneserver.protocols.HistoryListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fz.foodzoneserver.protocols.MessageWrapper.internal_static_foodzone_protocols_HistoryListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fz.foodzoneserver.protocols.MessageWrapper.internal_static_foodzone_protocols_HistoryListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fz.foodzoneserver.protocols.HistoryListResponse.class, com.fz.foodzoneserver.protocols.HistoryListResponse.Builder.class);
    }

    // Construct using com.fz.foodzoneserver.protocols.HistoryListResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOrderHistoryFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      result_ = "";

      if (orderHistoryBuilder_ == null) {
        orderHistory_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        orderHistoryBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fz.foodzoneserver.protocols.MessageWrapper.internal_static_foodzone_protocols_HistoryListResponse_descriptor;
    }

    @java.lang.Override
    public com.fz.foodzoneserver.protocols.HistoryListResponse getDefaultInstanceForType() {
      return com.fz.foodzoneserver.protocols.HistoryListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.fz.foodzoneserver.protocols.HistoryListResponse build() {
      com.fz.foodzoneserver.protocols.HistoryListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fz.foodzoneserver.protocols.HistoryListResponse buildPartial() {
      com.fz.foodzoneserver.protocols.HistoryListResponse result = new com.fz.foodzoneserver.protocols.HistoryListResponse(this);
      int from_bitField0_ = bitField0_;
      result.result_ = result_;
      if (orderHistoryBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          orderHistory_ = java.util.Collections.unmodifiableList(orderHistory_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.orderHistory_ = orderHistory_;
      } else {
        result.orderHistory_ = orderHistoryBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fz.foodzoneserver.protocols.HistoryListResponse) {
        return mergeFrom((com.fz.foodzoneserver.protocols.HistoryListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fz.foodzoneserver.protocols.HistoryListResponse other) {
      if (other == com.fz.foodzoneserver.protocols.HistoryListResponse.getDefaultInstance()) return this;
      if (!other.getResult().isEmpty()) {
        result_ = other.result_;
        onChanged();
      }
      if (orderHistoryBuilder_ == null) {
        if (!other.orderHistory_.isEmpty()) {
          if (orderHistory_.isEmpty()) {
            orderHistory_ = other.orderHistory_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOrderHistoryIsMutable();
            orderHistory_.addAll(other.orderHistory_);
          }
          onChanged();
        }
      } else {
        if (!other.orderHistory_.isEmpty()) {
          if (orderHistoryBuilder_.isEmpty()) {
            orderHistoryBuilder_.dispose();
            orderHistoryBuilder_ = null;
            orderHistory_ = other.orderHistory_;
            bitField0_ = (bitField0_ & ~0x00000001);
            orderHistoryBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrderHistoryFieldBuilder() : null;
          } else {
            orderHistoryBuilder_.addAllMessages(other.orderHistory_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fz.foodzoneserver.protocols.HistoryListResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fz.foodzoneserver.protocols.HistoryListResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object result_ = "";
    /**
     * <code>string result = 1;</code>
     * @return The result.
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string result = 1;</code>
     * @return The bytes for result.
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string result = 1;</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string result = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      
      result_ = getDefaultInstance().getResult();
      onChanged();
      return this;
    }
    /**
     * <code>string result = 1;</code>
     * @param value The bytes for result to set.
     * @return This builder for chaining.
     */
    public Builder setResultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      result_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.fz.foodzoneserver.protocols.Order> orderHistory_ =
      java.util.Collections.emptyList();
    private void ensureOrderHistoryIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        orderHistory_ = new java.util.ArrayList<com.fz.foodzoneserver.protocols.Order>(orderHistory_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.fz.foodzoneserver.protocols.Order, com.fz.foodzoneserver.protocols.Order.Builder, com.fz.foodzoneserver.protocols.OrderOrBuilder> orderHistoryBuilder_;

    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public java.util.List<com.fz.foodzoneserver.protocols.Order> getOrderHistoryList() {
      if (orderHistoryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orderHistory_);
      } else {
        return orderHistoryBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public int getOrderHistoryCount() {
      if (orderHistoryBuilder_ == null) {
        return orderHistory_.size();
      } else {
        return orderHistoryBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public com.fz.foodzoneserver.protocols.Order getOrderHistory(int index) {
      if (orderHistoryBuilder_ == null) {
        return orderHistory_.get(index);
      } else {
        return orderHistoryBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public Builder setOrderHistory(
        int index, com.fz.foodzoneserver.protocols.Order value) {
      if (orderHistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderHistoryIsMutable();
        orderHistory_.set(index, value);
        onChanged();
      } else {
        orderHistoryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public Builder setOrderHistory(
        int index, com.fz.foodzoneserver.protocols.Order.Builder builderForValue) {
      if (orderHistoryBuilder_ == null) {
        ensureOrderHistoryIsMutable();
        orderHistory_.set(index, builderForValue.build());
        onChanged();
      } else {
        orderHistoryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public Builder addOrderHistory(com.fz.foodzoneserver.protocols.Order value) {
      if (orderHistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderHistoryIsMutable();
        orderHistory_.add(value);
        onChanged();
      } else {
        orderHistoryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public Builder addOrderHistory(
        int index, com.fz.foodzoneserver.protocols.Order value) {
      if (orderHistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderHistoryIsMutable();
        orderHistory_.add(index, value);
        onChanged();
      } else {
        orderHistoryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public Builder addOrderHistory(
        com.fz.foodzoneserver.protocols.Order.Builder builderForValue) {
      if (orderHistoryBuilder_ == null) {
        ensureOrderHistoryIsMutable();
        orderHistory_.add(builderForValue.build());
        onChanged();
      } else {
        orderHistoryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public Builder addOrderHistory(
        int index, com.fz.foodzoneserver.protocols.Order.Builder builderForValue) {
      if (orderHistoryBuilder_ == null) {
        ensureOrderHistoryIsMutable();
        orderHistory_.add(index, builderForValue.build());
        onChanged();
      } else {
        orderHistoryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public Builder addAllOrderHistory(
        java.lang.Iterable<? extends com.fz.foodzoneserver.protocols.Order> values) {
      if (orderHistoryBuilder_ == null) {
        ensureOrderHistoryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orderHistory_);
        onChanged();
      } else {
        orderHistoryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public Builder clearOrderHistory() {
      if (orderHistoryBuilder_ == null) {
        orderHistory_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        orderHistoryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public Builder removeOrderHistory(int index) {
      if (orderHistoryBuilder_ == null) {
        ensureOrderHistoryIsMutable();
        orderHistory_.remove(index);
        onChanged();
      } else {
        orderHistoryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public com.fz.foodzoneserver.protocols.Order.Builder getOrderHistoryBuilder(
        int index) {
      return getOrderHistoryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public com.fz.foodzoneserver.protocols.OrderOrBuilder getOrderHistoryOrBuilder(
        int index) {
      if (orderHistoryBuilder_ == null) {
        return orderHistory_.get(index);  } else {
        return orderHistoryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public java.util.List<? extends com.fz.foodzoneserver.protocols.OrderOrBuilder> 
         getOrderHistoryOrBuilderList() {
      if (orderHistoryBuilder_ != null) {
        return orderHistoryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orderHistory_);
      }
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public com.fz.foodzoneserver.protocols.Order.Builder addOrderHistoryBuilder() {
      return getOrderHistoryFieldBuilder().addBuilder(
          com.fz.foodzoneserver.protocols.Order.getDefaultInstance());
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public com.fz.foodzoneserver.protocols.Order.Builder addOrderHistoryBuilder(
        int index) {
      return getOrderHistoryFieldBuilder().addBuilder(
          index, com.fz.foodzoneserver.protocols.Order.getDefaultInstance());
    }
    /**
     * <code>repeated .foodzone_protocols.Order orderHistory = 2;</code>
     */
    public java.util.List<com.fz.foodzoneserver.protocols.Order.Builder> 
         getOrderHistoryBuilderList() {
      return getOrderHistoryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.fz.foodzoneserver.protocols.Order, com.fz.foodzoneserver.protocols.Order.Builder, com.fz.foodzoneserver.protocols.OrderOrBuilder> 
        getOrderHistoryFieldBuilder() {
      if (orderHistoryBuilder_ == null) {
        orderHistoryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.fz.foodzoneserver.protocols.Order, com.fz.foodzoneserver.protocols.Order.Builder, com.fz.foodzoneserver.protocols.OrderOrBuilder>(
                orderHistory_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        orderHistory_ = null;
      }
      return orderHistoryBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:foodzone_protocols.HistoryListResponse)
  }

  // @@protoc_insertion_point(class_scope:foodzone_protocols.HistoryListResponse)
  private static final com.fz.foodzoneserver.protocols.HistoryListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fz.foodzoneserver.protocols.HistoryListResponse();
  }

  public static com.fz.foodzoneserver.protocols.HistoryListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HistoryListResponse>
      PARSER = new com.google.protobuf.AbstractParser<HistoryListResponse>() {
    @java.lang.Override
    public HistoryListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HistoryListResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HistoryListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HistoryListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fz.foodzoneserver.protocols.HistoryListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

