// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.fz.foodzoneserver.protocols;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodzone_protocols.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <code>optional .foodzone_protocols.UserInfo userInfo = 2;</code>
   * @return Whether the userInfo field is set.
   */
  boolean hasUserInfo();
  /**
   * <code>optional .foodzone_protocols.UserInfo userInfo = 2;</code>
   * @return The userInfo.
   */
  UserInfo getUserInfo();
  /**
   * <code>optional .foodzone_protocols.UserInfo userInfo = 2;</code>
   */
  UserInfoOrBuilder getUserInfoOrBuilder();
}
