// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.fz.foodzoneserver.protocols;

public final class MessageWrapper {
  private MessageWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodzone_protocols_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodzone_protocols_UserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodzone_protocols_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodzone_protocols_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodzone_protocols_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodzone_protocols_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodzone_protocols_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodzone_protocols_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodzone_protocols_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodzone_protocols_ServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031PATH/MessageWrapper.proto\022\022foodzone_pr" +
      "otocols\"k\n\010UserInfo\022\020\n\010username\030\001 \001(\t\022\020\n" +
      "\010fullname\030\002 \001(\t\022\n\n\002id\030\003 \001(\t\022\017\n\007address\030\004" +
      " \001(\t\022\r\n\005phone\030\005 \001(\t\022\017\n\007imgName\030\006 \001(\t\"2\n\014" +
      "LoginRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010passwo" +
      "rd\030\002 \001(\t\"a\n\rLoginResponse\022\016\n\006result\030\001 \001(" +
      "\t\0223\n\010userInfo\030\002 \001(\0132\034.foodzone_protocols" +
      ".UserInfoH\000\210\001\001B\013\n\t_userInfo\"b\n\rClientMes" +
      "sage\022\013\n\003msg\030\001 \001(\t\0228\n\014loginRequest\030\002 \001(\0132" +
      " .foodzone_protocols.LoginRequestH\000B\n\n\010r" +
      "equests\"e\n\rServerMessage\022\013\n\003msg\030\001 \001(\t\022:\n" +
      "\rloginResponse\030\002 \001(\0132!.foodzone_protocol" +
      "s.LoginResponseH\000B\013\n\tresponsesB#\n\037com.fz" +
      ".foodzoneserver.protocolsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_foodzone_protocols_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_foodzone_protocols_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodzone_protocols_UserInfo_descriptor,
        new java.lang.String[] { "Username", "Fullname", "Id", "Address", "Phone", "ImgName", });
    internal_static_foodzone_protocols_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_foodzone_protocols_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodzone_protocols_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_foodzone_protocols_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_foodzone_protocols_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodzone_protocols_LoginResponse_descriptor,
        new java.lang.String[] { "Result", "UserInfo", "UserInfo", });
    internal_static_foodzone_protocols_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_foodzone_protocols_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodzone_protocols_ClientMessage_descriptor,
        new java.lang.String[] { "Msg", "LoginRequest", "Requests", });
    internal_static_foodzone_protocols_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_foodzone_protocols_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodzone_protocols_ServerMessage_descriptor,
        new java.lang.String[] { "Msg", "LoginResponse", "Responses", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
