// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.fz.foodzoneserver.protocols;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodzone_protocols.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string desc = 2;</code>
   * @return The desc.
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 2;</code>
   * @return The bytes for desc.
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>string state = 3;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 3;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>string recipientName = 4;</code>
   * @return The recipientName.
   */
  java.lang.String getRecipientName();
  /**
   * <code>string recipientName = 4;</code>
   * @return The bytes for recipientName.
   */
  com.google.protobuf.ByteString
      getRecipientNameBytes();

  /**
   * <code>int32 price = 5;</code>
   * @return The price.
   */
  int getPrice();
}
