// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/MessageWrapper.proto

package com.fz.foodzoneserver.protocols;

/**
 * Protobuf type {@code foodzone_protocols.ServerMessage}
 */
public final class ServerMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:foodzone_protocols.ServerMessage)
    ServerMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerMessage.newBuilder() to construct.
  private ServerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerMessage() {
    msg_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServerMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            msg_ = s;
            break;
          }
          case 18: {
            LoginResponse.Builder subBuilder = null;
            if (responsesCase_ == 2) {
              subBuilder = ((LoginResponse) responses_).toBuilder();
            }
            responses_ =
                input.readMessage(LoginResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((LoginResponse) responses_);
              responses_ = subBuilder.buildPartial();
            }
            responsesCase_ = 2;
            break;
          }
          case 26: {
            RegisterResponse.Builder subBuilder = null;
            if (responsesCase_ == 3) {
              subBuilder = ((RegisterResponse) responses_).toBuilder();
            }
            responses_ =
                input.readMessage(RegisterResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((RegisterResponse) responses_);
              responses_ = subBuilder.buildPartial();
            }
            responsesCase_ = 3;
            break;
          }
          case 34: {
            UpdateInfoResponse.Builder subBuilder = null;
            if (responsesCase_ == 4) {
              subBuilder = ((UpdateInfoResponse) responses_).toBuilder();
            }
            responses_ =
                input.readMessage(UpdateInfoResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((UpdateInfoResponse) responses_);
              responses_ = subBuilder.buildPartial();
            }
            responsesCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MessageWrapper.internal_static_foodzone_protocols_ServerMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MessageWrapper.internal_static_foodzone_protocols_ServerMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ServerMessage.class, ServerMessage.Builder.class);
  }

  private int responsesCase_ = 0;
  private java.lang.Object responses_;
  public enum ResponsesCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LOGINRESPONSE(2),
    REGISTERRESPONSE(3),
    UPDATEINFORESPONSE(4),
    RESPONSES_NOT_SET(0);
    private final int value;
    private ResponsesCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponsesCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponsesCase forNumber(int value) {
      switch (value) {
        case 2: return LOGINRESPONSE;
        case 3: return REGISTERRESPONSE;
        case 4: return UPDATEINFORESPONSE;
        case 0: return RESPONSES_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponsesCase
  getResponsesCase() {
    return ResponsesCase.forNumber(
        responsesCase_);
  }

  public static final int MSG_FIELD_NUMBER = 1;
  private volatile java.lang.Object msg_;
  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  @java.lang.Override
  public java.lang.String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGINRESPONSE_FIELD_NUMBER = 2;
  /**
   * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
   * @return Whether the loginResponse field is set.
   */
  @java.lang.Override
  public boolean hasLoginResponse() {
    return responsesCase_ == 2;
  }
  /**
   * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
   * @return The loginResponse.
   */
  @java.lang.Override
  public LoginResponse getLoginResponse() {
    if (responsesCase_ == 2) {
       return (LoginResponse) responses_;
    }
    return LoginResponse.getDefaultInstance();
  }
  /**
   * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
   */
  @java.lang.Override
  public LoginResponseOrBuilder getLoginResponseOrBuilder() {
    if (responsesCase_ == 2) {
       return (LoginResponse) responses_;
    }
    return LoginResponse.getDefaultInstance();
  }

  public static final int REGISTERRESPONSE_FIELD_NUMBER = 3;
  /**
   * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
   * @return Whether the registerResponse field is set.
   */
  @java.lang.Override
  public boolean hasRegisterResponse() {
    return responsesCase_ == 3;
  }
  /**
   * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
   * @return The registerResponse.
   */
  @java.lang.Override
  public RegisterResponse getRegisterResponse() {
    if (responsesCase_ == 3) {
       return (RegisterResponse) responses_;
    }
    return RegisterResponse.getDefaultInstance();
  }
  /**
   * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
   */
  @java.lang.Override
  public RegisterResponseOrBuilder getRegisterResponseOrBuilder() {
    if (responsesCase_ == 3) {
       return (RegisterResponse) responses_;
    }
    return RegisterResponse.getDefaultInstance();
  }

  public static final int UPDATEINFORESPONSE_FIELD_NUMBER = 4;
  /**
   * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
   * @return Whether the updateInfoResponse field is set.
   */
  @java.lang.Override
  public boolean hasUpdateInfoResponse() {
    return responsesCase_ == 4;
  }
  /**
   * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
   * @return The updateInfoResponse.
   */
  @java.lang.Override
  public UpdateInfoResponse getUpdateInfoResponse() {
    if (responsesCase_ == 4) {
       return (UpdateInfoResponse) responses_;
    }
    return UpdateInfoResponse.getDefaultInstance();
  }
  /**
   * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
   */
  @java.lang.Override
  public UpdateInfoResponseOrBuilder getUpdateInfoResponseOrBuilder() {
    if (responsesCase_ == 4) {
       return (UpdateInfoResponse) responses_;
    }
    return UpdateInfoResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msg_);
    }
    if (responsesCase_ == 2) {
      output.writeMessage(2, (LoginResponse) responses_);
    }
    if (responsesCase_ == 3) {
      output.writeMessage(3, (RegisterResponse) responses_);
    }
    if (responsesCase_ == 4) {
      output.writeMessage(4, (UpdateInfoResponse) responses_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msg_);
    }
    if (responsesCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (LoginResponse) responses_);
    }
    if (responsesCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (RegisterResponse) responses_);
    }
    if (responsesCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (UpdateInfoResponse) responses_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ServerMessage)) {
      return super.equals(obj);
    }
    ServerMessage other = (ServerMessage) obj;

    if (!getMsg()
        .equals(other.getMsg())) return false;
    if (!getResponsesCase().equals(other.getResponsesCase())) return false;
    switch (responsesCase_) {
      case 2:
        if (!getLoginResponse()
            .equals(other.getLoginResponse())) return false;
        break;
      case 3:
        if (!getRegisterResponse()
            .equals(other.getRegisterResponse())) return false;
        break;
      case 4:
        if (!getUpdateInfoResponse()
            .equals(other.getUpdateInfoResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    switch (responsesCase_) {
      case 2:
        hash = (37 * hash) + LOGINRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getLoginResponse().hashCode();
        break;
      case 3:
        hash = (37 * hash) + REGISTERRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getRegisterResponse().hashCode();
        break;
      case 4:
        hash = (37 * hash) + UPDATEINFORESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateInfoResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ServerMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ServerMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ServerMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ServerMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ServerMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ServerMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ServerMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ServerMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ServerMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ServerMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ServerMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code foodzone_protocols.ServerMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:foodzone_protocols.ServerMessage)
		  ServerMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageWrapper.internal_static_foodzone_protocols_ServerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageWrapper.internal_static_foodzone_protocols_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServerMessage.class, ServerMessage.Builder.class);
    }

    // Construct using com.fz.foodzoneserver.protocols.ServerMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      msg_ = "";

      responsesCase_ = 0;
      responses_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MessageWrapper.internal_static_foodzone_protocols_ServerMessage_descriptor;
    }

    @java.lang.Override
    public ServerMessage getDefaultInstanceForType() {
      return ServerMessage.getDefaultInstance();
    }

    @java.lang.Override
    public ServerMessage build() {
      ServerMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ServerMessage buildPartial() {
      ServerMessage result = new ServerMessage(this);
      result.msg_ = msg_;
      if (responsesCase_ == 2) {
        if (loginResponseBuilder_ == null) {
          result.responses_ = responses_;
        } else {
          result.responses_ = loginResponseBuilder_.build();
        }
      }
      if (responsesCase_ == 3) {
        if (registerResponseBuilder_ == null) {
          result.responses_ = responses_;
        } else {
          result.responses_ = registerResponseBuilder_.build();
        }
      }
      if (responsesCase_ == 4) {
        if (updateInfoResponseBuilder_ == null) {
          result.responses_ = responses_;
        } else {
          result.responses_ = updateInfoResponseBuilder_.build();
        }
      }
      result.responsesCase_ = responsesCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ServerMessage) {
        return mergeFrom((ServerMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ServerMessage other) {
      if (other == ServerMessage.getDefaultInstance()) return this;
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        onChanged();
      }
      switch (other.getResponsesCase()) {
        case LOGINRESPONSE: {
          mergeLoginResponse(other.getLoginResponse());
          break;
        }
        case REGISTERRESPONSE: {
          mergeRegisterResponse(other.getRegisterResponse());
          break;
        }
        case UPDATEINFORESPONSE: {
          mergeUpdateInfoResponse(other.getUpdateInfoResponse());
          break;
        }
        case RESPONSES_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ServerMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ServerMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int responsesCase_ = 0;
    private java.lang.Object responses_;
    public ResponsesCase
        getResponsesCase() {
      return ResponsesCase.forNumber(
          responsesCase_);
    }

    public Builder clearResponses() {
      responsesCase_ = 0;
      responses_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object msg_ = "";
    /**
     * <code>string msg = 1;</code>
     * @return The msg.
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg = 1;</code>
     * @return The bytes for msg.
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg = 1;</code>
     * @param value The msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 1;</code>
     * @param value The bytes for msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msg_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
		    LoginResponse, LoginResponse.Builder, LoginResponseOrBuilder> loginResponseBuilder_;
    /**
     * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
     * @return Whether the loginResponse field is set.
     */
    @java.lang.Override
    public boolean hasLoginResponse() {
      return responsesCase_ == 2;
    }
    /**
     * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
     * @return The loginResponse.
     */
    @java.lang.Override
    public LoginResponse getLoginResponse() {
      if (loginResponseBuilder_ == null) {
        if (responsesCase_ == 2) {
          return (LoginResponse) responses_;
        }
        return LoginResponse.getDefaultInstance();
      } else {
        if (responsesCase_ == 2) {
          return loginResponseBuilder_.getMessage();
        }
        return LoginResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
     */
    public Builder setLoginResponse(LoginResponse value) {
      if (loginResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        responses_ = value;
        onChanged();
      } else {
        loginResponseBuilder_.setMessage(value);
      }
      responsesCase_ = 2;
      return this;
    }
    /**
     * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
     */
    public Builder setLoginResponse(
        LoginResponse.Builder builderForValue) {
      if (loginResponseBuilder_ == null) {
        responses_ = builderForValue.build();
        onChanged();
      } else {
        loginResponseBuilder_.setMessage(builderForValue.build());
      }
      responsesCase_ = 2;
      return this;
    }
    /**
     * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
     */
    public Builder mergeLoginResponse(LoginResponse value) {
      if (loginResponseBuilder_ == null) {
        if (responsesCase_ == 2 &&
            responses_ != LoginResponse.getDefaultInstance()) {
          responses_ = LoginResponse.newBuilder((LoginResponse) responses_)
              .mergeFrom(value).buildPartial();
        } else {
          responses_ = value;
        }
        onChanged();
      } else {
        if (responsesCase_ == 2) {
          loginResponseBuilder_.mergeFrom(value);
        }
        loginResponseBuilder_.setMessage(value);
      }
      responsesCase_ = 2;
      return this;
    }
    /**
     * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
     */
    public Builder clearLoginResponse() {
      if (loginResponseBuilder_ == null) {
        if (responsesCase_ == 2) {
          responsesCase_ = 0;
          responses_ = null;
          onChanged();
        }
      } else {
        if (responsesCase_ == 2) {
          responsesCase_ = 0;
          responses_ = null;
        }
        loginResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
     */
    public LoginResponse.Builder getLoginResponseBuilder() {
      return getLoginResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
     */
    @java.lang.Override
    public LoginResponseOrBuilder getLoginResponseOrBuilder() {
      if ((responsesCase_ == 2) && (loginResponseBuilder_ != null)) {
        return loginResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responsesCase_ == 2) {
          return (LoginResponse) responses_;
        }
        return LoginResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.foodzone_protocols.LoginResponse loginResponse = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
		    LoginResponse, LoginResponse.Builder, LoginResponseOrBuilder>
        getLoginResponseFieldBuilder() {
      if (loginResponseBuilder_ == null) {
        if (!(responsesCase_ == 2)) {
          responses_ = LoginResponse.getDefaultInstance();
        }
        loginResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
		        LoginResponse, LoginResponse.Builder, LoginResponseOrBuilder>(
                (LoginResponse) responses_,
                getParentForChildren(),
                isClean());
        responses_ = null;
      }
      responsesCase_ = 2;
      onChanged();;
      return loginResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
		    RegisterResponse, RegisterResponse.Builder, RegisterResponseOrBuilder> registerResponseBuilder_;
    /**
     * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
     * @return Whether the registerResponse field is set.
     */
    @java.lang.Override
    public boolean hasRegisterResponse() {
      return responsesCase_ == 3;
    }
    /**
     * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
     * @return The registerResponse.
     */
    @java.lang.Override
    public RegisterResponse getRegisterResponse() {
      if (registerResponseBuilder_ == null) {
        if (responsesCase_ == 3) {
          return (RegisterResponse) responses_;
        }
        return RegisterResponse.getDefaultInstance();
      } else {
        if (responsesCase_ == 3) {
          return registerResponseBuilder_.getMessage();
        }
        return RegisterResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
     */
    public Builder setRegisterResponse(RegisterResponse value) {
      if (registerResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        responses_ = value;
        onChanged();
      } else {
        registerResponseBuilder_.setMessage(value);
      }
      responsesCase_ = 3;
      return this;
    }
    /**
     * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
     */
    public Builder setRegisterResponse(
        RegisterResponse.Builder builderForValue) {
      if (registerResponseBuilder_ == null) {
        responses_ = builderForValue.build();
        onChanged();
      } else {
        registerResponseBuilder_.setMessage(builderForValue.build());
      }
      responsesCase_ = 3;
      return this;
    }
    /**
     * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
     */
    public Builder mergeRegisterResponse(RegisterResponse value) {
      if (registerResponseBuilder_ == null) {
        if (responsesCase_ == 3 &&
            responses_ != RegisterResponse.getDefaultInstance()) {
          responses_ = RegisterResponse.newBuilder((RegisterResponse) responses_)
              .mergeFrom(value).buildPartial();
        } else {
          responses_ = value;
        }
        onChanged();
      } else {
        if (responsesCase_ == 3) {
          registerResponseBuilder_.mergeFrom(value);
        }
        registerResponseBuilder_.setMessage(value);
      }
      responsesCase_ = 3;
      return this;
    }
    /**
     * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
     */
    public Builder clearRegisterResponse() {
      if (registerResponseBuilder_ == null) {
        if (responsesCase_ == 3) {
          responsesCase_ = 0;
          responses_ = null;
          onChanged();
        }
      } else {
        if (responsesCase_ == 3) {
          responsesCase_ = 0;
          responses_ = null;
        }
        registerResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
     */
    public RegisterResponse.Builder getRegisterResponseBuilder() {
      return getRegisterResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
     */
    @java.lang.Override
    public RegisterResponseOrBuilder getRegisterResponseOrBuilder() {
      if ((responsesCase_ == 3) && (registerResponseBuilder_ != null)) {
        return registerResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responsesCase_ == 3) {
          return (RegisterResponse) responses_;
        }
        return RegisterResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.foodzone_protocols.RegisterResponse registerResponse = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
		    RegisterResponse, RegisterResponse.Builder, RegisterResponseOrBuilder>
        getRegisterResponseFieldBuilder() {
      if (registerResponseBuilder_ == null) {
        if (!(responsesCase_ == 3)) {
          responses_ = RegisterResponse.getDefaultInstance();
        }
        registerResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
		        RegisterResponse, RegisterResponse.Builder, RegisterResponseOrBuilder>(
                (RegisterResponse) responses_,
                getParentForChildren(),
                isClean());
        responses_ = null;
      }
      responsesCase_ = 3;
      onChanged();;
      return registerResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
		    UpdateInfoResponse, UpdateInfoResponse.Builder, UpdateInfoResponseOrBuilder> updateInfoResponseBuilder_;
    /**
     * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
     * @return Whether the updateInfoResponse field is set.
     */
    @java.lang.Override
    public boolean hasUpdateInfoResponse() {
      return responsesCase_ == 4;
    }
    /**
     * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
     * @return The updateInfoResponse.
     */
    @java.lang.Override
    public UpdateInfoResponse getUpdateInfoResponse() {
      if (updateInfoResponseBuilder_ == null) {
        if (responsesCase_ == 4) {
          return (UpdateInfoResponse) responses_;
        }
        return UpdateInfoResponse.getDefaultInstance();
      } else {
        if (responsesCase_ == 4) {
          return updateInfoResponseBuilder_.getMessage();
        }
        return UpdateInfoResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
     */
    public Builder setUpdateInfoResponse(UpdateInfoResponse value) {
      if (updateInfoResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        responses_ = value;
        onChanged();
      } else {
        updateInfoResponseBuilder_.setMessage(value);
      }
      responsesCase_ = 4;
      return this;
    }
    /**
     * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
     */
    public Builder setUpdateInfoResponse(
        UpdateInfoResponse.Builder builderForValue) {
      if (updateInfoResponseBuilder_ == null) {
        responses_ = builderForValue.build();
        onChanged();
      } else {
        updateInfoResponseBuilder_.setMessage(builderForValue.build());
      }
      responsesCase_ = 4;
      return this;
    }
    /**
     * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
     */
    public Builder mergeUpdateInfoResponse(UpdateInfoResponse value) {
      if (updateInfoResponseBuilder_ == null) {
        if (responsesCase_ == 4 &&
            responses_ != UpdateInfoResponse.getDefaultInstance()) {
          responses_ = UpdateInfoResponse.newBuilder((UpdateInfoResponse) responses_)
              .mergeFrom(value).buildPartial();
        } else {
          responses_ = value;
        }
        onChanged();
      } else {
        if (responsesCase_ == 4) {
          updateInfoResponseBuilder_.mergeFrom(value);
        }
        updateInfoResponseBuilder_.setMessage(value);
      }
      responsesCase_ = 4;
      return this;
    }
    /**
     * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
     */
    public Builder clearUpdateInfoResponse() {
      if (updateInfoResponseBuilder_ == null) {
        if (responsesCase_ == 4) {
          responsesCase_ = 0;
          responses_ = null;
          onChanged();
        }
      } else {
        if (responsesCase_ == 4) {
          responsesCase_ = 0;
          responses_ = null;
        }
        updateInfoResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
     */
    public UpdateInfoResponse.Builder getUpdateInfoResponseBuilder() {
      return getUpdateInfoResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
     */
    @java.lang.Override
    public UpdateInfoResponseOrBuilder getUpdateInfoResponseOrBuilder() {
      if ((responsesCase_ == 4) && (updateInfoResponseBuilder_ != null)) {
        return updateInfoResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responsesCase_ == 4) {
          return (UpdateInfoResponse) responses_;
        }
        return UpdateInfoResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.foodzone_protocols.UpdateInfoResponse updateInfoResponse = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
		    UpdateInfoResponse, UpdateInfoResponse.Builder, UpdateInfoResponseOrBuilder>
        getUpdateInfoResponseFieldBuilder() {
      if (updateInfoResponseBuilder_ == null) {
        if (!(responsesCase_ == 4)) {
          responses_ = UpdateInfoResponse.getDefaultInstance();
        }
        updateInfoResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
		        UpdateInfoResponse, UpdateInfoResponse.Builder, UpdateInfoResponseOrBuilder>(
                (UpdateInfoResponse) responses_,
                getParentForChildren(),
                isClean());
        responses_ = null;
      }
      responsesCase_ = 4;
      onChanged();;
      return updateInfoResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:foodzone_protocols.ServerMessage)
  }

  // @@protoc_insertion_point(class_scope:foodzone_protocols.ServerMessage)
  private static final ServerMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ServerMessage();
  }

  public static ServerMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerMessage>
      PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
    @java.lang.Override
    public ServerMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServerMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServerMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ServerMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

